### PR TITLE
Binzard logo, as seen on slack

### PR DESCRIPTION
**Pull request by c42f**
"Conjuring binary elves since 2017"

Ok, I've now officially spent far too long on this :-)

I did some more fiddling to make the layout a bit better than the version I posted on slack.  Happy to change it a bit more, or change the embedded text to something more explanatory if you've got suggestions.

### CODE REVIEW

**Comment by c42f** [comment]
Current screenshot:

binzard

**Comment by c42f** [comment]
Hmm, I just noticed the original ascii art has an author attribution (which wasn't on the slack version):
https://www.ascii-code.com/ascii-art/people/occupations/wizards.php

Removing the attribution didn't seem quite right, so I've made a completely new one from scratch:
binzard4

**Comment by c42f** [comment]
There, I've changed the base branch so this merges to master.  @staticfloat did you want anything else changed here?

**Comment by staticfloat** [comment]
I love it @c42f; thanks for your invaluable contributions. :)

**Pull request merged**
