### PR TITLE
Require at least RegistryTools 2.1.0

### PR DESCRIPTION
**Pull request by DilumAluthge**
We need at least RegistryTools 2.1.0 so that we can get https://github.com/JuliaRegistries/RegistryTools.jl/pull/85.

### CODE REVIEW

**Comment by giordano** [comment]
You need to update the Manifest

**Comment by DilumAluthge** [comment]
Done. I used Julia 1.7.2 when updating the manifest.

Command I used to update the manifest:

```
add --preserve=all RegistryTools@2.1 Registrator@1.8
```

**Comment by giordano** [comment]
This is broken https://buildkite.com/julialang/yggdrasil/builds/1294#0186c3c4-a69f-4cef-b8f7-981600dc5f36, I'm going to revert this urgently

**Comment by GunnarFarneback** [comment]
To state the obvious, RegistryTools 2.0 bumped the major version because it was breaking.

**Pull request merged**
