### PR TITLE
Remove the version and arch strings more selectively.

### LINKED ISSUE #425: normalize_name cannot parse windows OpenSSL binary name
The binary names in discussion have format as below:

libcrypto-1_1-x64.dll
libssl-1_1-x64.dll
libcrypto-1_1.dll
libssl-1_1.dll

### PR DESCRIPTION
**Pull request by sambitdash**
Fixes #425

### CODE REVIEW

**Comment by giordano** [comment]
Hi, please note that binarybuilder is going to have a very large overhaul, see pull request #441. I don't know if this specific error is already fixed in that branch

**Comment by sambitdash** [comment]
> Hi, please note that binarybuilder is going to have a very large overhaul, see pull request #441. I don't know if this specific error is already fixed in that branch

This is great to know. Kindly, include this as I am forced to build OpenSSL for PDFIO build which unnecessarily slows down the test.

**Comment by giordano** [comment]
Note that openssl has been already built: https://github.com/JuliaBinaryWrappers/OpenSSL_jll.jl/releases/tag/OpenSSL-v1.1.1+0

**Comment by giordano** [comment]
If you need a build.jl,you can use this: https://github.com/giordano/FFMPEG.jl/blob/tmp/deps/build_OpenSSL.v1.1.1%2Bc.jl (please, copy the content as I may delete the branch at some point)

**Comment by sambitdash** [comment]
> If you need a build.jl,you can use this: https://github.com/giordano/FFMPEG.jl/blob/tmp/deps/build_OpenSSL.v1.1.1%2Bc.jl (please, copy the content as I may delete the branch at some point)

Thanks a lot. I think I will wait for a few days for the Julia 1.3 to be GA so that I can move to the wrapper binary packages. Those will be much easier to manage in the long run. I will also need the similar for zlib as well. 

For my requirements, this PR can be closed now.

**Comment by giordano** [comment]
Yes, both OpenSSL and Zlib are part of the wrappers already available, you can find the full list here: https://github.com/JuliaBinaryWrappers

**Pull request closed without merging**
