### PR TITLE
Bump to new rootfs

### PR DESCRIPTION
**Pull request by staticfloat**

### CODE REVIEW

**Comment by staticfloat** [comment]
@Keno it's happening here too now.  :(

**Comment by Keno** [comment]
Running an interactive build to can reproduce.

**Comment by Keno** [comment]
Looks like the rootfs is missing the `workspace` directory.

**Comment by Keno** [comment]
`/dev/null` and `/dev/ptmx` as well.

**Comment by Keno** [comment]
With that fixed, tests pass.

**Comment by staticfloat** [comment]
Ah, shoot.  My patches to fix that hadn't been merged yet.  Okay.  Rebuilding new rootfs.  Thank God for CI, and thank you for tracking that down for me.  :)

**Comment by staticfloat** [comment]
With that fixed, CI is passing, so I'm gonna go ahead and merge this.

**Pull request merged**
