### PR TITLE
tweak prose

### PR DESCRIPTION
**Pull request by KristofferC**
Could also put a `sir/madame` instead.

### CODE REVIEW

**Comment by ararslan** [comment]
If you want to keep the silly vibe, you could say, "Please specify how you would like to proceed, captain."

**Comment by staticfloat** [comment]
I enjoy the silly vibe, but whatever.  If we get rid of this, we should get rid of the comment above it as it's no longer true.

**Comment by KristofferC** [comment]
I don't care to be honest. I'm fine with leaving it. I don't think many people will get the reference though.

**Comment by davidanthoff** [comment]
I think you should merge this PR. Very few people will get the reference, and if you don't get it, the current language is not ok.

**Pull request closed without merging**
