### PR TITLE
Put upper bounds to compat of dependencies

### PR DESCRIPTION
**Pull request by giordano**
I hope I didn't miss any package.  This should allow auto-merge of https://github.com/JuliaRegistries/General/pull/6355

### CODE REVIEW

**Comment by staticfloat** [comment]
Do you know how we can tell codecov to be less strict?  It's annoying to always see it failing because coverage decreased by like `-0.11%` or something ridiculous like that.

**Comment by giordano** [comment]
Some time ago I found the option in coveralls to set a threshold, but not in codecov 😣

**Comment by staticfloat** [comment]
Perhaps this: https://docs.codecov.io/docs/commit-status

**Comment by giordano** [comment]
That looks like it!  I probably searched in the web interface only, but indeed codecov doesn't let you do much in the web interface

**Pull request merged**
