### PR TITLE
add static

### PR DESCRIPTION
**Pull request by matbesancon**
Adding static in the package and in the generated code

### CODE REVIEW

**Comment by matbesancon** [comment]
The error seems to come from a dependency not installed?
https://travis-ci.org/github/JuliaPackaging/BinaryBuilder.jl/jobs/673910227#L314

**Comment by giordano** [comment]
https://github.com/JuliaPackaging/BinaryBuilder.jl/pull/738 :wink:

**Comment by matbesancon** [comment]
thanks, just merged master

**Comment by staticfloat** [comment]
@matbesancon Hello!  Can you explain what you are trying to change here?

**Comment by matbesancon** [comment]
turning all checks on the julia version into static, since it can be done

**Comment by staticfloat** [comment]
I don't think `@static` has any effect at top-level; it's only useful within functions, since conditionals at the top-level will be determined at compile-time anyway.

**Comment by matbesancon** [comment]
ok, closing this

**Pull request closed without merging**
