### PR TITLE
Print PackageSpec correctly when printing build_tarball.jl

### PR DESCRIPTION
**Pull request by fredrikekre**
Print PackageSpec correctly when printing build_tarball.jl from the wizard.

Produces
```
dependencies = [
    PackageSpec(name="OpenSSL_jll", uuid="458c3c95-2e84-50aa-8efc-19380b2a3a95")
]
```
instead of
```
dependencies = [
    "PackageSpec(
  name = OpenSSL_jll
  uuid = 458c3c95-2e84-50aa-8efc-19380b2a3a95
  version = *
)",

]
```

### CODE REVIEW

**Comment by fredrikekre** [comment]
Looks like a download failure, can someone restart?

**Comment by fredrikekre** [comment]
Nightly failure is a Pkg bug.

**Comment by staticfloat** [comment]
I think `PackageSpec` needs a `UUID` object, not a string:

```
julia> PackageSpec(name="OpenSSL_jll", uuid="458c3c95-2e84-50aa-8efc-19380b2a3a95")
ERROR: MethodError: Cannot `convert` an object of type String to an object of type UUID
Closest candidates are:
  convert(::Type{T}, ::T) where T at essentials.jl:168
  UUID(::AbstractString) at uuid.jl:36
  UUID(::Any) at uuid.jl:9
Stacktrace:
 [1] convert(::Type{Union{Nothing, UUID}}, ::String) at ./some.jl:34
 [2] PackageSpec(::String, ::String, ::VersionSpec, ::Nothing, ::GitRepo, ::Nothing, ::Bool, ::PackageSpecialAction, ::PackageMode) at /home/sabae/tmp/julia-build/julia-release-1.3/usr/share/julia/stdlib/v1.3/Pkg/src/Types.jl:151
 [3] #PackageSpec#20(::String, ::String, ::VersionSpec, ::Nothing, ::GitRepo, ::Nothing, ::Bool, ::PackageSpecialAction, ::PackageMode, ::Type{PackageSpec}) at 
./util.jl:722
 [4] (::Core.var"#kw#Type")(::NamedTuple{(:name, :uuid),Tuple{String,String}}, ::Type{PackageSpec}) at ./none:0
 [5] top-level scope at REPL[6]:1
```

**Comment by fredrikekre** [comment]
Works for me on all Julia 1.X...

**Comment by staticfloat** [comment]
It's because I imported `Pkg.Types`.  That's annoying.

**Pull request merged**
