### PR TITLE
[AutoBuild] Precompile `__init__` in generated JLL wrappers

### PR DESCRIPTION
**Pull request by giordano**
Suggested by @vchuravy.  I haven't studied the impact of this though.

### CODE REVIEW

**Comment by vchuravy** [comment]
Curious what this does on the objcache PR as well xD

**Comment by giordano** [comment]
Alright, tomorrow I'll try to find some time to try it out on your branch.  I'll have to hack a few JLLs though.

**Comment by giordano** [comment]
Side note, it's quite sad we don't have a wrapper footer in `JLLWrappers` at the moment, otherwise we could put the precompile statement there.  Apparently top-level expressions don't like referencing functions not yet defined (which I guess makes sense) :-(

**Comment by giordano** [comment]
What I measured: the minimum output of
```
./julia --startup-file=no --project=/tmp -E '@elapsed @eval using <package name>'
```
out of 20 runs.

How I patched up the files:
```
find ~/.julia/packages -wholename '*_jll/*/src/wrappers/*.jl' -exec sed -i.bak 's/end  # __init__()/end; precompile(__init__, ())/' '{}' \;
```

`OpenSpecFun_jll`:
<table>
<tr>
	<td> Julia commit
	<td> Without precompile
	<td> With precompile
<tr>
	<td> https://github.com/JuliaLang/julia/commit/b1c67ea8a020667d840091ba681fdcdafde5d38c (`master`)
	<td> 0.073126158
	<td> 0.073017225
<tr>
	<td> https://github.com/JuliaLang/julia/commit/f9063bd99ef560cfd1ee3ca5041b90a12078b1b3 (https://github.com/JuliaLang/julia/pull/47184)
	<td> 0.05832722
	<td> 0.057778371
</table>

`GTK3_jll`:
<table>
<tr>
	<td> Julia commit
	<td> Without precompile
	<td> With precompile
<tr>
	<td> https://github.com/JuliaLang/julia/commit/b1c67ea8a020667d840091ba681fdcdafde5d38c (`master`)
	<td> 0.132819175
	<td> 0.132805276
<tr>
	<td> https://github.com/JuliaLang/julia/commit/f9063bd99ef560cfd1ee3ca5041b90a12078b1b3 (https://github.com/JuliaLang/julia/pull/47184)
	<td> 0.121388042
	<td> 0.122004996
</table>

Adding `precompile(__init__, ())` doesn't seem to give a significant performance boost.

**Comment by vchuravy** [comment]
Fair enough. It would still be interesting to see why we spend so much time compiling when loading a jll.

**Comment by giordano** [comment]
I tried to force precompilation of some functions in JLLWrappers with
```diff
diff --git a/src/products/executable_generators.jl b/src/products/executable_generators.jl
index cceffe6..d50c9c6 100644
--- a/src/products/executable_generators.jl
+++ b/src/products/executable_generators.jl
@@ -40,6 +40,7 @@ function declare_old_executable_product(product_name)
         end
     end
 end
+declare_old_executable_product(:product_name)
 
 function declare_new_executable_product(product_name)
     @static if VERSION < v"1.6.0-DEV"
@@ -78,6 +79,7 @@ function declare_new_executable_product(product_name)
         end
     end
 end
+declare_new_executable_product(:product_name)
 
 macro declare_executable_product(product_name)
     path_name = string(product_name, "_path")
diff --git a/src/products/library_generators.jl b/src/products/library_generators.jl
index 6a1c877..f019b57 100644
--- a/src/products/library_generators.jl
+++ b/src/products/library_generators.jl
@@ -46,6 +46,7 @@ function init_new_library_product(product_name)
         end
     end
 end
+init_new_library_product(:product_name)
 
 macro init_library_product(product_name, product_path, dlopen_flags)
     handle_name = Symbol(string(product_name, "_handle"))
diff --git a/src/toplevel_generators.jl b/src/toplevel_generators.jl
index 7295d37..2a8eb3e 100644
--- a/src/toplevel_generators.jl
+++ b/src/toplevel_generators.jl
@@ -41,6 +41,7 @@ function generate_imports(src_name)
         end
     end
 end
+generate_imports("src_name")
 
 """
     generate_compiler_options(src_name)
@@ -66,6 +67,7 @@ function generate_compiler_options(src_name)
     # If none of these are available, TOUGH BEANS.
     return nothing
 end
+generate_compiler_options("src_name")
 
 """
     generate_toplevel_definitions(src_name)
@@ -93,6 +95,7 @@ function generate_toplevel_definitions(src_name, __source__)
         dev_jll() = Base.invokelatest(JLLWrappers.dev_jll, $(src_name))
     end
 end
+generate_toplevel_definitions("src_name", LineNumberNode(1, ""))
 
 """
     generate_wrapper_load(src_name, pkg_uuid)
@@ -194,6 +197,7 @@ function generate_wrapper_load(src_name, pkg_uuid, __source__)
         end
     end
 end
+generate_wrapper_load("src_name", Base.UUID("00000000-1111-2222-3333-444444444444"), LineNumberNode(1, ""))
 
 macro generate_main_file_header(src_name)
     return excat(
diff --git a/src/wrapper_generators.jl b/src/wrapper_generators.jl
index 3be7f20..b064c8a 100644
--- a/src/wrapper_generators.jl
+++ b/src/wrapper_generators.jl
@@ -71,3 +71,4 @@ function emit_preference_path_load(pref_name)
         end
     end
 end
+emit_preference_path_load("pref_name")
```
but also with this change I don't see much difference.

**Comment by giordano** [comment]
Closing as this didn't seem worth it.  Also, we should have a footer in JLLWrappers.

**Pull request closed without merging**
