### PR TITLE
dont ratelimit people

### PR DESCRIPTION
**Pull request by KristofferC**

### CODE REVIEW

**Comment by KristofferC** [comment]
CI:

```
GitHub releases build.jl reconstruction: Error During Test
  Got an exception of type ErrorException outside of a @test
  Error found in GitHub reponse:
  	Status Code: 403
  	Message: API rate limit exceeded for 35.188.1.99. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
  	Docs URL: https://developer.github.com/v3/#rate-limiting
  	Errors:
```

image

**Comment by staticfloat** [comment]
Is this because you want to set `ENV["GITHUB_TOKEN"]` from within Julia, but after you've run `using BinaryBuilder`?

**Comment by staticfloat** [comment]
Nevermind, I saw https://github.com/JuliaPackaging/BinaryBuilder.jl/issues/286

This is worrying though, as the travis setup for this repo actually sets `GITHUB_AUTH` (I actually think we should name this `GITHUB_TOKEN` to mirror other services) so I suspect something is broken here.

**Comment by KristofferC** [comment]
Added some debug output and I get:

```
!!!!!!!! QUERYING GITHUB AUTH !!!!!!!!
get(ENV, "GITHUB_AUTH", "") = ""
length(get(ENV, "GITHUB_AUTH", "")) = 0
```

so is the env variable getting removed somewhere?

**Comment by staticfloat** [comment]
Where did you put that code?  I don't see it in the Travis output.

**Comment by KristofferC** [comment]
I put it here: https://github.com/JuliaPackaging/BinaryBuilder.jl/pull/287/commits/ed6a85678e44adcd31c86d3e3492a96b29d459ca

Here is a link to the output for one of the Travis logs: https://travis-ci.org/JuliaPackaging/BinaryBuilder.jl/jobs/393261367#L726-L728

**Comment by staticfloat** [comment]
Well I should have read the log more carefully.

https://travis-ci.org/JuliaPackaging/BinaryBuilder.jl/jobs/393261367#L459-L460

```
Encrypted environment variables have been removed for security reasons.
See https://docs.travis-ci.com/user/pull-requests/#Pull-Requests-and-Security-Restrictions
```

Womp womp.  I also went through the trouble of renaming `GITHUB_AUTH` to `GITHUB_TOKEN` to match other tools more closely.  I've merged your PR (with that rename included).  Thanks!

**Pull request closed without merging**
