### PR TITLE
Iterate over `readmeta` results

### PR DESCRIPTION
**Pull request by eschnett**

### CODE REVIEW

**Comment by eschnett** [comment]
I couldn't run the test suite because
```
[13:48:09] ../meson.build:1:0: ERROR: Unable to detect linker for compiler `/opt/bin/x86_64-apple-darwin14-libgfortran4-cxx11-julia_version+1.7.3/x86_64-apple-darwin14-clang++ -Wl,--version -L/workspace/destdir/lib -fuse-ld=/opt/bin/x86_64-apple-darwin14-libgfortran4-cxx11-julia_version+1.7.3/x86_64-apple-darwin14-ld`
[13:48:09] stdout:
[13:48:09] stderr: ld: warning: directory not found for option '-L/workspace/destdir/lib'
[13:48:09] ld: unknown option: --version
[13:48:09] clang-16: error: linker command failed with exit code 1 (use -v to see invocation)
```

That is, it fails because the Apple linkers aren't set up correctly. I think it's the same problem as https://github.com/JuliaPackaging/Yggdrasil/issues/7745.

**Comment by eschnett** [comment]
The meson build failure happens for me locally but not in CI.

**Comment by giordano** [comment]
We probably need to update BinaryBuilderBase first: https://github.com/JuliaPackaging/BinaryBuilderBase.jl/blob/6faea2ef758b089156f35716d0f55dc74a8ab786/test/Project.toml#L16

**Comment by eschnett** [comment]
This PR depends on https://github.com/JuliaPackaging/BinaryBuilderBase.jl/pull/363.

**Comment by eschnett** [comment]
This PR probably needs to disable ObjectFile 0.3. Should I do this, or should I add a function with a `@static if` condition to handle both versions?

**Comment by giordano** [comment]
Only v0.4 is fine

**Comment by eschnett** [comment]
It seems `Manifest.toml` is committed into the repository. Should I updated it as well? Or should I remove it?

**Comment by giordano** [comment]
I'm not a fan of committing the Manifest in packages, but let's update it for the time being.

**Pull request merged**
