### PR TITLE
Small fixes

### PR DESCRIPTION
**Pull request by staticfloat**

### CODE REVIEW

**Comment by giordano** [comment]
While you are at it, you may also want to fix https://github.com/JuliaPackaging/Yggdrasil/pull/222#issuecomment-557823497.  I think this is a consequence of https://github.com/JuliaRegistries/Registrator.jl/pull/247

**Comment by staticfloat** [comment]
Yes, we should; I think we need to move over to `RegistryTools.jl` :(

**Comment by ararslan** [comment]
As a stopgap to fix automatic registration for JLLs until things are ported over to RegistryTools, we can set an upper bound on Registrator to the breaking version. Right now we have the Registrator dependency fixed to semver-compatible with Registrator 1.0, but a recent 1.x version broke BinaryBuilder.

**Comment by ararslan** [comment]
See #517

**Pull request merged**
