### PR TITLE
Wizard: Don't ignore error paths

### PR DESCRIPTION
**Pull request by Keno**
Also a minimal fix to #677. This is on top of #678 because it touches some of the files and I'm hoping we can merge that soon-ish. If not I can do the rebase dance to switch the order of these though.

### CODE REVIEW

**Comment by Keno** [comment]
Rebased and updated base branch.

**Comment by Keno** [comment]
1.4 test failure is due to rc2 not liking something we do. Also happens on master.

**Comment by giordano** [comment]
Is it only when using the wizard?  We use Julia 1.4 on Yggdrasil

**Comment by Keno** [comment]
Yes, it's in the wizard, but it literally just started failing because 1.4rc2 contains a Pkg bump. Wouldn't be surprised if something else broke as well.

**Pull request merged**
