### PR TITLE
Fix hanging tests

### PR DESCRIPTION
**Pull request by giordano**

### CODE REVIEW

**Comment by giordano** [comment]
@staticfloat jobs are hanging at
```
[ Info: Start setting up the server...
[ Info: creating tarball...
[ Info: Registering artifact...
[ Info: Creating server...
[ Info: Trying port 14444
[ Info: Yggdrasil directory: /data/staticfloat/bb_azp/rootfs/agent_2/_work/1/s/deps/Yggdrasil
[ Info: Cloning bare Yggdrasil into deps/Yggdrasil...
[ Info: Yggdrasil directory: /data/staticfloat/bb_azp/rootfs/agent_2/_work/1/s/deps/Yggdrasil
```
https://github.com/JuliaPackaging/BinaryBuilder.jl/blob/24a318e03a226633ee8d36fd5605e7d787c7c355/src/wizard/yggdrasil.jl#L6-L11
Can you please check what's going on in that directory?

**Comment by giordano** [comment]
Nevermind, that was a red herring, it's actually hanging at
```
[ Info: Start setting up the server...
[ Info: creating tarball...
[ Info: Registering artifact...
[ Info: Creating server...
[ Info: Trying port 14444
[ Info: port 14444 is good, move on
[ Info: /data/staticfloat/bb_azp/rootfs/agent_1/_work/1/s/test/wizard.jl:90
[ Info: /data/staticfloat/bb_azp/rootfs/agent_1/_work/1/s/test/wizard.jl:127
[ Info: /data/staticfloat/bb_azp/rootfs/agent_1/_work/1/s/test/wizard.jl:130
┌ Info: Using cached git repository
│   url = "[https://github.com/JuliaPackaging/Yggdrasil.git"](https://github.com/JuliaPackaging/Yggdrasil.git%22)
└   repo_path = "/data/staticfloat/bb_azp/rootfs/agent_1/storage/downloads/clones/Yggdrasil.git-a5a98df475347605e8bd1e4db910f627874e12e32c926834f439d470461da54b"
[ Info: Updating bare Yggdrasil clone in deps/Yggdrasil...
[ Info: /data/staticfloat/bb_azp/rootfs/agent_1/_work/1/s/test/wizard.jl:136
[ Info: /data/staticfloat/bb_azp/rootfs/agent_1/_work/1/s/test/wizard.jl:141
[ Info: /data/staticfloat/bb_azp/rootfs/agent_1/_work/1/s/test/wizard.jl:143
┌ Info: Using cached git repository
│   url = "[https://github.com/JuliaPackaging/Yggdrasil.git"](https://github.com/JuliaPackaging/Yggdrasil.git%22)
└   repo_path = "/data/staticfloat/bb_azp/rootfs/agent_1/storage/downloads/clones/Yggdrasil.git-a5a98df475347605e8bd1e4db910f627874e12e32c926834f439d470461da54b"
[ Info: /data/staticfloat/bb_azp/rootfs/agent_1/_work/1/s/test/wizard.jl:145
```
which is https://github.com/JuliaPackaging/BinaryBuilder.jl/blob/ad805cb7627d648b55b56c5b3189da81148bf532/test/wizard.jl#L144-L145, but it's weird, we haven't touched the [`src/wizard`](https://github.com/JuliaPackaging/BinaryBuilder.jl/tree/45b9ee380e6d6ffe606ced4483749ae7e51839e9/src/wizard) directory since January 10th, _way_ before tests started hanging.

**Comment by giordano** [comment]
Ok, good news is that I get the hang at the same point also locally, so at least it should be easier to debug.  I'll try to find some time next week.  Still weird this is happening only now....

**Comment by giordano** [comment]
Oh, I see, it's because of https://github.com/JuliaPackaging/Yggdrasil/pull/4472 :facepalm: :facepalm:

**Comment by staticfloat** [comment]
How ironic.

**Pull request merged**
