### PR TITLE
Use RegistryTools for interacting with the registry

### PR DESCRIPTION
**Pull request by ararslan**
The registry editing functionality was removed from Registrator in version 1.0.1.

Alternative to #517.

### CODE REVIEW

**Comment by giordano** [comment]
As a way forward I think this is better than #517.  Glad it was that easy, thank you so much!

**Comment by ararslan** [comment]
I didn't test it though so hopefully this actually works 😛

**Comment by ararslan** [comment]
Ugh, checked in manifests are very annoying. I'm not sure how to update the docs one appropriately.

**Comment by staticfloat** [comment]
It's easy; you just `julia --project=docs` then `pkg> update`.  That's it.

**Comment by staticfloat** [comment]
I rebased and changed a few things around; My test to ensure that things work [looks good](https://github.com/JuliaRegistries/General/pull/5868), so we're merging.

**Pull request merged**
