### PR TITLE
A simpler way of disabling Codecov commit statuses

### PR DESCRIPTION
**Pull request by DilumAluthge**
Based on https://docs.codecov.io/docs/commit-status#disabling-a-status

### CODE REVIEW

**Review by giordano — COMMENTED** [review]
I don't think the goal was to completely disable codecov commit statuses (at least that wasn't my intention and I added those lines: #550) but rather have lower thresholds

**Comment by DilumAluthge** [comment]
Is a threshold of 1% useful in practice? Would it make sense to pick slightly higher thresholds?

**Comment by giordano** [comment]
The problem is more that I don't really understand how the thresholds work (allowing something like ~ -5% would be ok, but still good to report larger drops) and settings of codecov have always been very confusing to me.

**Comment by DilumAluthge** [comment]
Okay I see what you want to do. Let me make a new PR.

**Comment by DilumAluthge** [comment]
My earlier comment was mistaken. The problem is not the threshold, it's the target. You basically never want to set the target to something as low as 1%. See https://github.com/JuliaPackaging/BinaryBuilder.jl/pull/1049

**Pull request closed without merging**
